// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjNivwB-QJYWXTyG4ZYGseTVqKJelIdDs',
    appId: '1:35154838808:web:b118583c01992be5e94a6d',
    messagingSenderId: '35154838808',
    projectId: 'jetchat-d3642',
    authDomain: 'jetchat-d3642.firebaseapp.com',
    storageBucket: 'jetchat-d3642.firebasestorage.app',
    measurementId: 'G-VG80NDE9S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUyTvjtkn8rEdV5mQq59BT06nZCgQSWZk',
    appId: '1:35154838808:android:a5e5106eb8b3267be94a6d',
    messagingSenderId: '35154838808',
    projectId: 'jetchat-d3642',
    storageBucket: 'jetchat-d3642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSg-CMuKcI9tY9B2USprr7_4Tz4Wd1Rlo',
    appId: '1:35154838808:ios:81fd7384d78d79f5e94a6d',
    messagingSenderId: '35154838808',
    projectId: 'jetchat-d3642',
    storageBucket: 'jetchat-d3642.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSg-CMuKcI9tY9B2USprr7_4Tz4Wd1Rlo',
    appId: '1:35154838808:ios:81fd7384d78d79f5e94a6d',
    messagingSenderId: '35154838808',
    projectId: 'jetchat-d3642',
    storageBucket: 'jetchat-d3642.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjNivwB-QJYWXTyG4ZYGseTVqKJelIdDs',
    appId: '1:35154838808:web:b448f98bfcbe4b84e94a6d',
    messagingSenderId: '35154838808',
    projectId: 'jetchat-d3642',
    authDomain: 'jetchat-d3642.firebaseapp.com',
    storageBucket: 'jetchat-d3642.firebasestorage.app',
    measurementId: 'G-SG98FMSL1S',
  );
}
